### PR TITLE
Pages/home

### PR DESCRIPTION
**Pull request by manish591**
### Added home page for e-commerce application.

### CODE REVIEW

**Comment by scjuly19** [comment]
- Code looks fine but it would be nice if you can host it on netlify so that UI can be seen and reviewed too.

**Review by scjuly19 — APPROVED** [review]

**Comment by manish591** [comment]
> * Code looks fine but it would be nice if you can host it on netlify so that UI can be seen and reviewed too.

 I like to host only when I've finished my work. If you want to see UI then you can also open this is codesandbox.

**Review by shrey27 — APPROVED** [review]
UI looks nice. I like the responsive part and usage of drawers with navbar.
PR is good to merge.

**Comment by manish591** [comment]
> UI looks nice. I like the responsive part and usage of drawers with navbar. PR is good to merge.

Thanks

**Pull request merged**
