### PR TITLE
Pages/wishlist

### PR DESCRIPTION
**Pull request by manish591**
Added wishlist page for e-commerce application. 

Here is the code sandbox link https://4pzrx.csb.app/pages/wishlist.html

### CODE REVIEW

**Review by romabulani — APPROVED** [review]
Looks good to merge
Suggestion : You should always add value to alt attribute in img tag

**Comment by manish591** [comment]
> Looks good to merge Suggestion : You should always add value to alt attribute in img tag

These are not the final images that I'm going to use. So, that's why I didn't add an alternative.

**Comment by romabulani** [comment]
> > Looks good to merge Suggestion : You should always add value to alt attribute in img tag
> 
> These are not the final images that I'm going to use. So, that's why I didn't add an alternative.

Ok, understood

**Review by rahulbakshi4 — APPROVED** [review]
The code looks good here is a suggestion to consider :
 - For the move to cart button add some hover styling 
 - For the same button try changing the text color too as the contrast ratio of this not very try good, to get the contrast ratio above 4. 
 PR is good to merge upon considering these few changes

**Comment by manish591** [comment]
> The code looks good here is a suggestion to consider :
> 
> * For the move to cart button add some hover styling
> * For the same button try changing the text color too as the contrast ratio of this not very try good, to get the contrast ratio above 4.
>   PR is good to merge upon considering these few changes

I have added the hover styling. But, the contrast ratio is already 5.84.

**Pull request merged**
